In [2]:
#Experiment14
#Experiment to understand feature scaling. 

In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# New dataset
data = {
    "Study_Hours": [2, 4, 6, 8, 10],
    "Test_Score": [45, 55, 65, 80, 95],
    "Attendance": [60, 70, 75, 85, 95]
}

df = pd.DataFrame(data)

print("Original Dataset:")
print(df)

# Standard Scaling
sc = StandardScaler()
standard_scaled = sc.fit_transform(df)

print("\nStandard Scaled Data:")
print(standard_scaled)

# Min-Max Scaling
mms = MinMaxScaler()
minmax_scaled = mms.fit_transform(df)

print("\nMin-Max Scaled Data:")
print(minmax_scaled)

Original Dataset:
   Study_Hours  Test_Score  Attendance
0            2          45          60
1            4          55          70
2            6          65          75
3            8          80          85
4           10          95          95

Standard Scaled Data:
[[-1.41421356 -1.29385109 -1.40693001]
 [-0.70710678 -0.73130714 -0.57932412]
 [ 0.         -0.16876319 -0.16552118]
 [ 0.70710678  0.67505274  0.66208471]
 [ 1.41421356  1.51886867  1.4896906 ]]

Min-Max Scaled Data:
[[0.         0.         0.        ]
 [0.25       0.2        0.28571429]
 [0.5        0.4        0.42857143]
 [0.75       0.7        0.71428571]
 [1.         1.         1.        ]]
